//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/15/2021 3:36:16 PM
namespace Reference
{
    
    /// <summary>
    /// There are no comments for XS_PU_SAMPLINGPLAN in the schema.
    /// </summary>
    public partial class XS_PU_SAMPLINGPLAN : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new XS_PU_SAMPLINGPLAN object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public XS_PU_SAMPLINGPLAN(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "production.pu.XS_PU_SAMPLINGPLAN", "Reference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Reference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("production.pu.XS_PU_SAMPLINGPLAN.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for SAMPLINGPLAN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SAMPLINGPLANType> SAMPLINGPLAN
        {
            get
            {
                if ((this._SAMPLINGPLAN == null))
                {
                    this._SAMPLINGPLAN = base.CreateQuery<SAMPLINGPLANType>("SAMPLINGPLAN");
                }
                return this._SAMPLINGPLAN;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SAMPLINGPLANType> _SAMPLINGPLAN;
        /// <summary>
        /// There are no comments for SAMPLINGPLAN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSAMPLINGPLAN(SAMPLINGPLANType sAMPLINGPLANType)
        {
            base.AddObject("SAMPLINGPLAN", sAMPLINGPLANType);
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_SAMPLINGPLAN.SAMPLINGPLANType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SAMPLINGPLAN")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class SAMPLINGPLANType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SAMPLINGPLANType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SAMPLINGPLANType CreateSAMPLINGPLANType(string ID)
        {
            SAMPLINGPLANType sAMPLINGPLANType = new SAMPLINGPLANType();
            sAMPLINGPLANType.ID = ID;
            return sAMPLINGPLANType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PART_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PART_NO
        {
            get
            {
                return this._PART_NO;
            }
            set
            {
                this.OnPART_NOChanging(value);
                this._PART_NO = value;
                this.OnPART_NOChanged();
                this.OnPropertyChanged("PART_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PART_NO;
        partial void OnPART_NOChanging(string value);
        partial void OnPART_NOChanged();
        /// <summary>
        /// There are no comments for Property SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SITE
        {
            get
            {
                return this._SITE;
            }
            set
            {
                this.OnSITEChanging(value);
                this._SITE = value;
                this.OnSITEChanged();
                this.OnPropertyChanged("SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SITE;
        partial void OnSITEChanging(string value);
        partial void OnSITEChanged();
        /// <summary>
        /// There are no comments for Property MATERIAL_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MATERIAL_GROUP
        {
            get
            {
                return this._MATERIAL_GROUP;
            }
            set
            {
                this.OnMATERIAL_GROUPChanging(value);
                this._MATERIAL_GROUP = value;
                this.OnMATERIAL_GROUPChanged();
                this.OnPropertyChanged("MATERIAL_GROUP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MATERIAL_GROUP;
        partial void OnMATERIAL_GROUPChanging(string value);
        partial void OnMATERIAL_GROUPChanged();
        /// <summary>
        /// There are no comments for Property TASK_LIST_TYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TASK_LIST_TYPE
        {
            get
            {
                return this._TASK_LIST_TYPE;
            }
            set
            {
                this.OnTASK_LIST_TYPEChanging(value);
                this._TASK_LIST_TYPE = value;
                this.OnTASK_LIST_TYPEChanged();
                this.OnPropertyChanged("TASK_LIST_TYPE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TASK_LIST_TYPE;
        partial void OnTASK_LIST_TYPEChanging(string value);
        partial void OnTASK_LIST_TYPEChanged();
        /// <summary>
        /// There are no comments for Property GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GROUP
        {
            get
            {
                return this._GROUP;
            }
            set
            {
                this.OnGROUPChanging(value);
                this._GROUP = value;
                this.OnGROUPChanged();
                this.OnPropertyChanged("GROUP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GROUP;
        partial void OnGROUPChanging(string value);
        partial void OnGROUPChanged();
        /// <summary>
        /// There are no comments for Property GRP_CTR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GRP_CTR
        {
            get
            {
                return this._GRP_CTR;
            }
            set
            {
                this.OnGRP_CTRChanging(value);
                this._GRP_CTR = value;
                this.OnGRP_CTRChanged();
                this.OnPropertyChanged("GRP_CTR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GRP_CTR;
        partial void OnGRP_CTRChanging(string value);
        partial void OnGRP_CTRChanged();
        /// <summary>
        /// There are no comments for Property COUNTER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COUNTER
        {
            get
            {
                return this._COUNTER;
            }
            set
            {
                this.OnCOUNTERChanging(value);
                this._COUNTER = value;
                this.OnCOUNTERChanged();
                this.OnPropertyChanged("COUNTER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COUNTER;
        partial void OnCOUNTERChanging(string value);
        partial void OnCOUNTERChanged();
        /// <summary>
        /// There are no comments for Property TASK_LIST_NODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TASK_LIST_NODE
        {
            get
            {
                return this._TASK_LIST_NODE;
            }
            set
            {
                this.OnTASK_LIST_NODEChanging(value);
                this._TASK_LIST_NODE = value;
                this.OnTASK_LIST_NODEChanged();
                this.OnPropertyChanged("TASK_LIST_NODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TASK_LIST_NODE;
        partial void OnTASK_LIST_NODEChanging(string value);
        partial void OnTASK_LIST_NODEChanged();
        /// <summary>
        /// There are no comments for Property BASE_QTY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BASE_QTY
        {
            get
            {
                return this._BASE_QTY;
            }
            set
            {
                this.OnBASE_QTYChanging(value);
                this._BASE_QTY = value;
                this.OnBASE_QTYChanged();
                this.OnPropertyChanged("BASE_QTY");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BASE_QTY;
        partial void OnBASE_QTYChanging(string value);
        partial void OnBASE_QTYChanged();
        /// <summary>
        /// There are no comments for Property CHAR_TYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CHAR_TYPE
        {
            get
            {
                return this._CHAR_TYPE;
            }
            set
            {
                this.OnCHAR_TYPEChanging(value);
                this._CHAR_TYPE = value;
                this.OnCHAR_TYPEChanged();
                this.OnPropertyChanged("CHAR_TYPE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CHAR_TYPE;
        partial void OnCHAR_TYPEChanging(string value);
        partial void OnCHAR_TYPEChanged();
        /// <summary>
        /// There are no comments for Property INSP_CHAR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSP_CHAR
        {
            get
            {
                return this._INSP_CHAR;
            }
            set
            {
                this.OnINSP_CHARChanging(value);
                this._INSP_CHAR = value;
                this.OnINSP_CHARChanged();
                this.OnPropertyChanged("INSP_CHAR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSP_CHAR;
        partial void OnINSP_CHARChanging(string value);
        partial void OnINSP_CHARChanged();
        /// <summary>
        /// There are no comments for Property SMPL_PROC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SMPL_PROC
        {
            get
            {
                return this._SMPL_PROC;
            }
            set
            {
                this.OnSMPL_PROCChanging(value);
                this._SMPL_PROC = value;
                this.OnSMPL_PROCChanged();
                this.OnPropertyChanged("SMPL_PROC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SMPL_PROC;
        partial void OnSMPL_PROCChanging(string value);
        partial void OnSMPL_PROCChanged();
        /// <summary>
        /// There are no comments for Property VERSION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VERSION
        {
            get
            {
                return this._VERSION;
            }
            set
            {
                this.OnVERSIONChanging(value);
                this._VERSION = value;
                this.OnVERSIONChanged();
                this.OnPropertyChanged("VERSION");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VERSION;
        partial void OnVERSIONChanging(string value);
        partial void OnVERSIONChanged();
        /// <summary>
        /// There are no comments for Property MSTRCHAR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MSTRCHAR
        {
            get
            {
                return this._MSTRCHAR;
            }
            set
            {
                this.OnMSTRCHARChanging(value);
                this._MSTRCHAR = value;
                this.OnMSTRCHARChanged();
                this.OnPropertyChanged("MSTRCHAR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MSTRCHAR;
        partial void OnMSTRCHARChanging(string value);
        partial void OnMSTRCHARChanged();
        /// <summary>
        /// There are no comments for Property QM_CTRL_KEY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QM_CTRL_KEY
        {
            get
            {
                return this._QM_CTRL_KEY;
            }
            set
            {
                this.OnQM_CTRL_KEYChanging(value);
                this._QM_CTRL_KEY = value;
                this.OnQM_CTRL_KEYChanged();
                this.OnPropertyChanged("QM_CTRL_KEY");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QM_CTRL_KEY;
        partial void OnQM_CTRL_KEYChanging(string value);
        partial void OnQM_CTRL_KEYChanged();
        /// <summary>
        /// There are no comments for Property CERT_TYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CERT_TYPE
        {
            get
            {
                return this._CERT_TYPE;
            }
            set
            {
                this.OnCERT_TYPEChanging(value);
                this._CERT_TYPE = value;
                this.OnCERT_TYPEChanged();
                this.OnPropertyChanged("CERT_TYPE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CERT_TYPE;
        partial void OnCERT_TYPEChanging(string value);
        partial void OnCERT_TYPEChanged();
        /// <summary>
        /// There are no comments for Property INSP_SETUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSP_SETUP
        {
            get
            {
                return this._INSP_SETUP;
            }
            set
            {
                this.OnINSP_SETUPChanging(value);
                this._INSP_SETUP = value;
                this.OnINSP_SETUPChanged();
                this.OnPropertyChanged("INSP_SETUP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSP_SETUP;
        partial void OnINSP_SETUPChanging(string value);
        partial void OnINSP_SETUPChanged();
        /// <summary>
        /// There are no comments for Property QM_ACTIVE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QM_ACTIVE
        {
            get
            {
                return this._QM_ACTIVE;
            }
            set
            {
                this.OnQM_ACTIVEChanging(value);
                this._QM_ACTIVE = value;
                this.OnQM_ACTIVEChanged();
                this.OnPropertyChanged("QM_ACTIVE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QM_ACTIVE;
        partial void OnQM_ACTIVEChanging(string value);
        partial void OnQM_ACTIVEChanged();
        /// <summary>
        /// There are no comments for Property INSP_SHORT_TEXT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSP_SHORT_TEXT
        {
            get
            {
                return this._INSP_SHORT_TEXT;
            }
            set
            {
                this.OnINSP_SHORT_TEXTChanging(value);
                this._INSP_SHORT_TEXT = value;
                this.OnINSP_SHORT_TEXTChanged();
                this.OnPropertyChanged("INSP_SHORT_TEXT");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSP_SHORT_TEXT;
        partial void OnINSP_SHORT_TEXTChanging(string value);
        partial void OnINSP_SHORT_TEXTChanged();
        /// <summary>
        /// There are no comments for Property CREATED_ON in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CREATED_ON
        {
            get
            {
                return this._CREATED_ON;
            }
            set
            {
                this.OnCREATED_ONChanging(value);
                this._CREATED_ON = value;
                this.OnCREATED_ONChanged();
                this.OnPropertyChanged("CREATED_ON");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CREATED_ON;
        partial void OnCREATED_ONChanging(string value);
        partial void OnCREATED_ONChanged();
        /// <summary>
        /// There are no comments for Property VALID_DATE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VALID_DATE
        {
            get
            {
                return this._VALID_DATE;
            }
            set
            {
                this.OnVALID_DATEChanging(value);
                this._VALID_DATE = value;
                this.OnVALID_DATEChanged();
                this.OnPropertyChanged("VALID_DATE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VALID_DATE;
        partial void OnVALID_DATEChanging(string value);
        partial void OnVALID_DATEChanged();
        /// <summary>
        /// There are no comments for Property DELETE_IND in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DELETE_IND
        {
            get
            {
                return this._DELETE_IND;
            }
            set
            {
                this.OnDELETE_INDChanging(value);
                this._DELETE_IND = value;
                this.OnDELETE_INDChanged();
                this.OnPropertyChanged("DELETE_IND");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DELETE_IND;
        partial void OnDELETE_INDChanging(string value);
        partial void OnDELETE_INDChanged();
        /// <summary>
        /// There are no comments for Property INACTIVE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INACTIVE
        {
            get
            {
                return this._INACTIVE;
            }
            set
            {
                this.OnINACTIVEChanging(value);
                this._INACTIVE = value;
                this.OnINACTIVEChanged();
                this.OnPropertyChanged("INACTIVE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INACTIVE;
        partial void OnINACTIVEChanging(string value);
        partial void OnINACTIVEChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
