//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/26/2022 6:58:25 PM
namespace production.pu.XS_PU_EIQC_SUPPLIER
{
    
    /// <summary>
    /// There are no comments for XS_PU_EIQC_SUPPLIER in the schema.
    /// </summary>
    public partial class XS_PU_EIQC_SUPPLIER : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new XS_PU_EIQC_SUPPLIER object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public XS_PU_EIQC_SUPPLIER(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for SUPPLIER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SUPPLIERType> SUPPLIER
        {
            get
            {
                if ((this._SUPPLIER == null))
                {
                    this._SUPPLIER = base.CreateQuery<SUPPLIERType>("SUPPLIER");
                }
                return this._SUPPLIER;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SUPPLIERType> _SUPPLIER;
        /// <summary>
        /// There are no comments for InputParams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<InputParamsType> InputParams
        {
            get
            {
                if ((this._InputParams == null))
                {
                    this._InputParams = base.CreateQuery<InputParamsType>("InputParams");
                }
                return this._InputParams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<InputParamsType> _InputParams;
        /// <summary>
        /// There are no comments for SUPPLIER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSUPPLIER(SUPPLIERType sUPPLIERType)
        {
            base.AddObject("SUPPLIER", sUPPLIERType);
        }
        /// <summary>
        /// There are no comments for InputParams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInputParams(InputParamsType inputParamsType)
        {
            base.AddObject("InputParams", inputParamsType);
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_EIQC_SUPPLIER.SUPPLIERType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SUPPLIER")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class SUPPLIERType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SUPPLIERType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SUPPLIERType CreateSUPPLIERType(string ID)
        {
            SUPPLIERType sUPPLIERType = new SUPPLIERType();
            sUPPLIERType.ID = ID;
            return sUPPLIERType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SITE_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SITE_NAME
        {
            get
            {
                return this._SITE_NAME;
            }
            set
            {
                this.OnSITE_NAMEChanging(value);
                this._SITE_NAME = value;
                this.OnSITE_NAMEChanged();
                this.OnPropertyChanged("SITE_NAME");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SITE_NAME;
        partial void OnSITE_NAMEChanging(string value);
        partial void OnSITE_NAMEChanged();
        /// <summary>
        /// There are no comments for Property SITE_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SITE_CODE
        {
            get
            {
                return this._SITE_CODE;
            }
            set
            {
                this.OnSITE_CODEChanging(value);
                this._SITE_CODE = value;
                this.OnSITE_CODEChanged();
                this.OnPropertyChanged("SITE_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SITE_CODE;
        partial void OnSITE_CODEChanging(string value);
        partial void OnSITE_CODEChanged();
        /// <summary>
        /// There are no comments for Property EMAIL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EMAIL
        {
            get
            {
                return this._EMAIL;
            }
            set
            {
                this.OnEMAILChanging(value);
                this._EMAIL = value;
                this.OnEMAILChanged();
                this.OnPropertyChanged("EMAIL");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EMAIL;
        partial void OnEMAILChanging(string value);
        partial void OnEMAILChanged();
        /// <summary>
        /// There are no comments for Property PHONE_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PHONE_NO
        {
            get
            {
                return this._PHONE_NO;
            }
            set
            {
                this.OnPHONE_NOChanging(value);
                this._PHONE_NO = value;
                this.OnPHONE_NOChanged();
                this.OnPropertyChanged("PHONE_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PHONE_NO;
        partial void OnPHONE_NOChanging(string value);
        partial void OnPHONE_NOChanged();
        /// <summary>
        /// There are no comments for Property FAX_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FAX_NO
        {
            get
            {
                return this._FAX_NO;
            }
            set
            {
                this.OnFAX_NOChanging(value);
                this._FAX_NO = value;
                this.OnFAX_NOChanged();
                this.OnPropertyChanged("FAX_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FAX_NO;
        partial void OnFAX_NOChanging(string value);
        partial void OnFAX_NOChanged();
        /// <summary>
        /// There are no comments for Property VENDOR_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_CODE
        {
            get
            {
                return this._VENDOR_CODE;
            }
            set
            {
                this.OnVENDOR_CODEChanging(value);
                this._VENDOR_CODE = value;
                this.OnVENDOR_CODEChanged();
                this.OnPropertyChanged("VENDOR_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_CODE;
        partial void OnVENDOR_CODEChanging(string value);
        partial void OnVENDOR_CODEChanged();
        /// <summary>
        /// There are no comments for Property VENDOR_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_NAME
        {
            get
            {
                return this._VENDOR_NAME;
            }
            set
            {
                this.OnVENDOR_NAMEChanging(value);
                this._VENDOR_NAME = value;
                this.OnVENDOR_NAMEChanged();
                this.OnPropertyChanged("VENDOR_NAME");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_NAME;
        partial void OnVENDOR_NAMEChanging(string value);
        partial void OnVENDOR_NAMEChanged();
        /// <summary>
        /// There are no comments for Property VENDOR_NAME2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_NAME2
        {
            get
            {
                return this._VENDOR_NAME2;
            }
            set
            {
                this.OnVENDOR_NAME2Changing(value);
                this._VENDOR_NAME2 = value;
                this.OnVENDOR_NAME2Changed();
                this.OnPropertyChanged("VENDOR_NAME2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_NAME2;
        partial void OnVENDOR_NAME2Changing(string value);
        partial void OnVENDOR_NAME2Changed();
        /// <summary>
        /// There are no comments for Property VENDOR_NAME3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_NAME3
        {
            get
            {
                return this._VENDOR_NAME3;
            }
            set
            {
                this.OnVENDOR_NAME3Changing(value);
                this._VENDOR_NAME3 = value;
                this.OnVENDOR_NAME3Changed();
                this.OnPropertyChanged("VENDOR_NAME3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_NAME3;
        partial void OnVENDOR_NAME3Changing(string value);
        partial void OnVENDOR_NAME3Changed();
        /// <summary>
        /// There are no comments for Property VENDOR_NAME4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_NAME4
        {
            get
            {
                return this._VENDOR_NAME4;
            }
            set
            {
                this.OnVENDOR_NAME4Changing(value);
                this._VENDOR_NAME4 = value;
                this.OnVENDOR_NAME4Changed();
                this.OnPropertyChanged("VENDOR_NAME4");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_NAME4;
        partial void OnVENDOR_NAME4Changing(string value);
        partial void OnVENDOR_NAME4Changed();
        /// <summary>
        /// There are no comments for Property IC_SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IC_SITE
        {
            get
            {
                return this._IC_SITE;
            }
            set
            {
                this.OnIC_SITEChanging(value);
                this._IC_SITE = value;
                this.OnIC_SITEChanged();
                this.OnPropertyChanged("IC_SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IC_SITE;
        partial void OnIC_SITEChanging(string value);
        partial void OnIC_SITEChanged();
        /// <summary>
        /// There are no comments for Property VENDOR_ACCT_GRP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_ACCT_GRP
        {
            get
            {
                return this._VENDOR_ACCT_GRP;
            }
            set
            {
                this.OnVENDOR_ACCT_GRPChanging(value);
                this._VENDOR_ACCT_GRP = value;
                this.OnVENDOR_ACCT_GRPChanged();
                this.OnPropertyChanged("VENDOR_ACCT_GRP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_ACCT_GRP;
        partial void OnVENDOR_ACCT_GRPChanging(string value);
        partial void OnVENDOR_ACCT_GRPChanged();
        /// <summary>
        /// There are no comments for Property PURCHASE_ORG in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PURCHASE_ORG
        {
            get
            {
                return this._PURCHASE_ORG;
            }
            set
            {
                this.OnPURCHASE_ORGChanging(value);
                this._PURCHASE_ORG = value;
                this.OnPURCHASE_ORGChanged();
                this.OnPropertyChanged("PURCHASE_ORG");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PURCHASE_ORG;
        partial void OnPURCHASE_ORGChanging(string value);
        partial void OnPURCHASE_ORGChanged();
        /// <summary>
        /// There are no comments for Property SALES_ORG_POC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SALES_ORG_POC
        {
            get
            {
                return this._SALES_ORG_POC;
            }
            set
            {
                this.OnSALES_ORG_POCChanging(value);
                this._SALES_ORG_POC = value;
                this.OnSALES_ORG_POCChanged();
                this.OnPropertyChanged("SALES_ORG_POC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SALES_ORG_POC;
        partial void OnSALES_ORG_POCChanging(string value);
        partial void OnSALES_ORG_POCChanged();
        /// <summary>
        /// There are no comments for Property COMPANY_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMPANY_CODE
        {
            get
            {
                return this._COMPANY_CODE;
            }
            set
            {
                this.OnCOMPANY_CODEChanging(value);
                this._COMPANY_CODE = value;
                this.OnCOMPANY_CODEChanged();
                this.OnPropertyChanged("COMPANY_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMPANY_CODE;
        partial void OnCOMPANY_CODEChanging(string value);
        partial void OnCOMPANY_CODEChanged();
        /// <summary>
        /// There are no comments for Property VALUATION_AREA in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VALUATION_AREA
        {
            get
            {
                return this._VALUATION_AREA;
            }
            set
            {
                this.OnVALUATION_AREAChanging(value);
                this._VALUATION_AREA = value;
                this.OnVALUATION_AREAChanged();
                this.OnPropertyChanged("VALUATION_AREA");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VALUATION_AREA;
        partial void OnVALUATION_AREAChanging(string value);
        partial void OnVALUATION_AREAChanged();
        /// <summary>
        /// There are no comments for Property IC_VENDOR_OF_PLANT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IC_VENDOR_OF_PLANT
        {
            get
            {
                return this._IC_VENDOR_OF_PLANT;
            }
            set
            {
                this.OnIC_VENDOR_OF_PLANTChanging(value);
                this._IC_VENDOR_OF_PLANT = value;
                this.OnIC_VENDOR_OF_PLANTChanged();
                this.OnPropertyChanged("IC_VENDOR_OF_PLANT");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IC_VENDOR_OF_PLANT;
        partial void OnIC_VENDOR_OF_PLANTChanging(string value);
        partial void OnIC_VENDOR_OF_PLANTChanged();
        /// <summary>
        /// There are no comments for Property CREATED_DATE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CREATED_DATE
        {
            get
            {
                return this._CREATED_DATE;
            }
            set
            {
                this.OnCREATED_DATEChanging(value);
                this._CREATED_DATE = value;
                this.OnCREATED_DATEChanged();
                this.OnPropertyChanged("CREATED_DATE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CREATED_DATE;
        partial void OnCREATED_DATEChanging(string value);
        partial void OnCREATED_DATEChanged();
        /// <summary>
        /// There are no comments for Property ADDRESS_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ADDRESS_NO
        {
            get
            {
                return this._ADDRESS_NO;
            }
            set
            {
                this.OnADDRESS_NOChanging(value);
                this._ADDRESS_NO = value;
                this.OnADDRESS_NOChanged();
                this.OnPropertyChanged("ADDRESS_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ADDRESS_NO;
        partial void OnADDRESS_NOChanging(string value);
        partial void OnADDRESS_NOChanged();
        /// <summary>
        /// There are no comments for Property STREET_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string STREET_NO
        {
            get
            {
                return this._STREET_NO;
            }
            set
            {
                this.OnSTREET_NOChanging(value);
                this._STREET_NO = value;
                this.OnSTREET_NOChanged();
                this.OnPropertyChanged("STREET_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _STREET_NO;
        partial void OnSTREET_NOChanging(string value);
        partial void OnSTREET_NOChanged();
        /// <summary>
        /// There are no comments for Property CITY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CITY
        {
            get
            {
                return this._CITY;
            }
            set
            {
                this.OnCITYChanging(value);
                this._CITY = value;
                this.OnCITYChanged();
                this.OnPropertyChanged("CITY");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CITY;
        partial void OnCITYChanging(string value);
        partial void OnCITYChanged();
        /// <summary>
        /// There are no comments for Property POSTAL_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string POSTAL_CODE
        {
            get
            {
                return this._POSTAL_CODE;
            }
            set
            {
                this.OnPOSTAL_CODEChanging(value);
                this._POSTAL_CODE = value;
                this.OnPOSTAL_CODEChanged();
                this.OnPropertyChanged("POSTAL_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _POSTAL_CODE;
        partial void OnPOSTAL_CODEChanging(string value);
        partial void OnPOSTAL_CODEChanged();
        /// <summary>
        /// There are no comments for Property COUNTRY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COUNTRY
        {
            get
            {
                return this._COUNTRY;
            }
            set
            {
                this.OnCOUNTRYChanging(value);
                this._COUNTRY = value;
                this.OnCOUNTRYChanged();
                this.OnPropertyChanged("COUNTRY");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COUNTRY;
        partial void OnCOUNTRYChanging(string value);
        partial void OnCOUNTRYChanged();
        /// <summary>
        /// There are no comments for Property REGION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string REGION
        {
            get
            {
                return this._REGION;
            }
            set
            {
                this.OnREGIONChanging(value);
                this._REGION = value;
                this.OnREGIONChanged();
                this.OnPropertyChanged("REGION");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _REGION;
        partial void OnREGIONChanging(string value);
        partial void OnREGIONChanged();
        /// <summary>
        /// There are no comments for Property LAND_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LAND_CODE
        {
            get
            {
                return this._LAND_CODE;
            }
            set
            {
                this.OnLAND_CODEChanging(value);
                this._LAND_CODE = value;
                this.OnLAND_CODEChanged();
                this.OnPropertyChanged("LAND_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LAND_CODE;
        partial void OnLAND_CODEChanging(string value);
        partial void OnLAND_CODEChanged();
        /// <summary>
        /// There are no comments for Property STATUS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string STATUS
        {
            get
            {
                return this._STATUS;
            }
            set
            {
                this.OnSTATUSChanging(value);
                this._STATUS = value;
                this.OnSTATUSChanged();
                this.OnPropertyChanged("STATUS");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _STATUS;
        partial void OnSTATUSChanging(string value);
        partial void OnSTATUSChanged();
        /// <summary>
        /// There are no comments for Property SEARCH_TERM in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SEARCH_TERM
        {
            get
            {
                return this._SEARCH_TERM;
            }
            set
            {
                this.OnSEARCH_TERMChanging(value);
                this._SEARCH_TERM = value;
                this.OnSEARCH_TERMChanged();
                this.OnPropertyChanged("SEARCH_TERM");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SEARCH_TERM;
        partial void OnSEARCH_TERMChanging(string value);
        partial void OnSEARCH_TERMChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_EIQC_SUPPLIER.InputParamsType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IP_SITE
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("InputParams")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IP_SITE")]
    public partial class InputParamsType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property IP_SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IP_SITE
        {
            get
            {
                return this._IP_SITE;
            }
            set
            {
                this.OnIP_SITEChanging(value);
                this._IP_SITE = value;
                this.OnIP_SITEChanged();
                this.OnPropertyChanged("IP_SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IP_SITE = "Site";
        partial void OnIP_SITEChanging(string value);
        partial void OnIP_SITEChanged();
        /// <summary>
        /// There are no comments for SUPPLIER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SUPPLIERType> SUPPLIER
        {
            get
            {
                return this._SUPPLIER;
            }
            set
            {
                this._SUPPLIER = value;
                this.OnPropertyChanged("SUPPLIER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SUPPLIERType> _SUPPLIER = new global::System.Data.Services.Client.DataServiceCollection<SUPPLIERType>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
