//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 8/23/2020 1:26:07 AM
namespace SAPHana.Model
{
    /// <summary>
    /// There are no comments for JCASVendorModelSingle in the schema.
    /// </summary>
    public partial class JCASVendorModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<JCASVendorModel>
    {
        /// <summary>
        /// Initialize a new JCASVendorModelSingle object.
        /// </summary>
        public JCASVendorModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new JCASVendorModelSingle object.
        /// </summary>
        public JCASVendorModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new JCASVendorModelSingle object.
        /// </summary>
        public JCASVendorModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<JCASVendorModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for JCASVendorModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// JCASVendorId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("JCASVendorId")]
    public partial class JCASVendorModel : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new JCASVendorModel object.
        /// </summary>
        /// <param name="jCASVendorId">Initial value of JCASVendorId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static JCASVendorModel CreateJCASVendorModel(string jCASVendorId)
        {
            JCASVendorModel jCASVendorModel = new JCASVendorModel();
            jCASVendorModel.JCASVendorId = jCASVendorId;
            return jCASVendorModel;
        }
        /// <summary>
        /// There are no comments for Property JCASVendorId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string JCASVendorId
        {
            get
            {
                return this._JCASVendorId;
            }
            set
            {
                this.OnJCASVendorIdChanging(value);
                this._JCASVendorId = value;
                this.OnJCASVendorIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _JCASVendorId;
        partial void OnJCASVendorIdChanging(string value);
        partial void OnJCASVendorIdChanged();
        /// <summary>
        /// There are no comments for Property VENDORCODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string VENDORCODE
        {
            get
            {
                return this._VENDORCODE;
            }
            set
            {
                this.OnVENDORCODEChanging(value);
                this._VENDORCODE = value;
                this.OnVENDORCODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _VENDORCODE;
        partial void OnVENDORCODEChanging(string value);
        partial void OnVENDORCODEChanged();
        /// <summary>
        /// There are no comments for Property VENDORNAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string VENDORNAME
        {
            get
            {
                return this._VENDORNAME;
            }
            set
            {
                this.OnVENDORNAMEChanging(value);
                this._VENDORNAME = value;
                this.OnVENDORNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _VENDORNAME;
        partial void OnVENDORNAMEChanging(string value);
        partial void OnVENDORNAMEChanged();
        /// <summary>
        /// There are no comments for Property DELETEFLAG in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string DELETEFLAG
        {
            get
            {
                return this._DELETEFLAG;
            }
            set
            {
                this.OnDELETEFLAGChanging(value);
                this._DELETEFLAG = value;
                this.OnDELETEFLAGChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DELETEFLAG;
        partial void OnDELETEFLAGChanging(string value);
        partial void OnDELETEFLAGChanged();
        /// <summary>
        /// There are no comments for Property KTOKK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string KTOKK
        {
            get
            {
                return this._KTOKK;
            }
            set
            {
                this.OnKTOKKChanging(value);
                this._KTOKK = value;
                this.OnKTOKKChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _KTOKK;
        partial void OnKTOKKChanging(string value);
        partial void OnKTOKKChanged();
    }
    /// <summary>
    /// There are no comments for JCASMPNModelSingle in the schema.
    /// </summary>
    public partial class JCASMPNModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<JCASMPNModel>
    {
        /// <summary>
        /// Initialize a new JCASMPNModelSingle object.
        /// </summary>
        public JCASMPNModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new JCASMPNModelSingle object.
        /// </summary>
        public JCASMPNModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new JCASMPNModelSingle object.
        /// </summary>
        public JCASMPNModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<JCASMPNModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for JCASMPNModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// JCASMPNId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("JCASMPNId")]
    public partial class JCASMPNModel : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new JCASMPNModel object.
        /// </summary>
        /// <param name="jCASMPNId">Initial value of JCASMPNId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static JCASMPNModel CreateJCASMPNModel(string jCASMPNId)
        {
            JCASMPNModel jCASMPNModel = new JCASMPNModel();
            jCASMPNModel.JCASMPNId = jCASMPNId;
            return jCASMPNModel;
        }
        /// <summary>
        /// There are no comments for Property JCASMPNId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string JCASMPNId
        {
            get
            {
                return this._JCASMPNId;
            }
            set
            {
                this.OnJCASMPNIdChanging(value);
                this._JCASMPNId = value;
                this.OnJCASMPNIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _JCASMPNId;
        partial void OnJCASMPNIdChanging(string value);
        partial void OnJCASMPNIdChanged();
        /// <summary>
        /// There are no comments for Property MFRPARTID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> MFRPARTID
        {
            get
            {
                return this._MFRPARTID;
            }
            set
            {
                this.OnMFRPARTIDChanging(value);
                this._MFRPARTID = value;
                this.OnMFRPARTIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _MFRPARTID;
        partial void OnMFRPARTIDChanging(global::System.Nullable<int> value);
        partial void OnMFRPARTIDChanged();
        /// <summary>
        /// There are no comments for Property MFRPARTCODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string MFRPARTCODE
        {
            get
            {
                return this._MFRPARTCODE;
            }
            set
            {
                this.OnMFRPARTCODEChanging(value);
                this._MFRPARTCODE = value;
                this.OnMFRPARTCODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MFRPARTCODE;
        partial void OnMFRPARTCODEChanging(string value);
        partial void OnMFRPARTCODEChanged();
        /// <summary>
        /// There are no comments for Property AMLREFERENCE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string AMLREFERENCE
        {
            get
            {
                return this._AMLREFERENCE;
            }
            set
            {
                this.OnAMLREFERENCEChanging(value);
                this._AMLREFERENCE = value;
                this.OnAMLREFERENCEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AMLREFERENCE;
        partial void OnAMLREFERENCEChanging(string value);
        partial void OnAMLREFERENCEChanged();
        /// <summary>
        /// There are no comments for Property CORPORATIONID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> CORPORATIONID
        {
            get
            {
                return this._CORPORATIONID;
            }
            set
            {
                this.OnCORPORATIONIDChanging(value);
                this._CORPORATIONID = value;
                this.OnCORPORATIONIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _CORPORATIONID;
        partial void OnCORPORATIONIDChanging(global::System.Nullable<int> value);
        partial void OnCORPORATIONIDChanged();
        /// <summary>
        /// There are no comments for Property CORPORATIONNAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string CORPORATIONNAME
        {
            get
            {
                return this._CORPORATIONNAME;
            }
            set
            {
                this.OnCORPORATIONNAMEChanging(value);
                this._CORPORATIONNAME = value;
                this.OnCORPORATIONNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CORPORATIONNAME;
        partial void OnCORPORATIONNAMEChanging(string value);
        partial void OnCORPORATIONNAMEChanged();
    }
    /// <summary>
    /// There are no comments for SitePartModelSingle in the schema.
    /// </summary>
    public partial class SitePartModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<SitePartModel>
    {
        /// <summary>
        /// Initialize a new SitePartModelSingle object.
        /// </summary>
        public SitePartModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SitePartModelSingle object.
        /// </summary>
        public SitePartModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SitePartModelSingle object.
        /// </summary>
        public SitePartModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<SitePartModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for SitePartModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    public partial class SitePartModel : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new SitePartModel object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static SitePartModel CreateSitePartModel(string ID)
        {
            SitePartModel sitePartModel = new SitePartModel();
            sitePartModel.ID = ID;
            return sitePartModel;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SITECODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SITECODE
        {
            get
            {
                return this._SITECODE;
            }
            set
            {
                this.OnSITECODEChanging(value);
                this._SITECODE = value;
                this.OnSITECODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SITECODE;
        partial void OnSITECODEChanging(string value);
        partial void OnSITECODEChanged();
        /// <summary>
        /// There are no comments for Property SITEPARTCODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SITEPARTCODE
        {
            get
            {
                return this._SITEPARTCODE;
            }
            set
            {
                this.OnSITEPARTCODEChanging(value);
                this._SITEPARTCODE = value;
                this.OnSITEPARTCODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SITEPARTCODE;
        partial void OnSITEPARTCODEChanging(string value);
        partial void OnSITEPARTCODEChanged();
        /// <summary>
        /// There are no comments for Property SITEPARTTYPECODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SITEPARTTYPECODE
        {
            get
            {
                return this._SITEPARTTYPECODE;
            }
            set
            {
                this.OnSITEPARTTYPECODEChanging(value);
                this._SITEPARTTYPECODE = value;
                this.OnSITEPARTTYPECODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SITEPARTTYPECODE;
        partial void OnSITEPARTTYPECODEChanging(string value);
        partial void OnSITEPARTTYPECODEChanged();
        /// <summary>
        /// There are no comments for Property SITEPARTDESCRIPTION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SITEPARTDESCRIPTION
        {
            get
            {
                return this._SITEPARTDESCRIPTION;
            }
            set
            {
                this.OnSITEPARTDESCRIPTIONChanging(value);
                this._SITEPARTDESCRIPTION = value;
                this.OnSITEPARTDESCRIPTIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SITEPARTDESCRIPTION;
        partial void OnSITEPARTDESCRIPTIONChanging(string value);
        partial void OnSITEPARTDESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for Property LOTSIZECODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string LOTSIZECODE
        {
            get
            {
                return this._LOTSIZECODE;
            }
            set
            {
                this.OnLOTSIZECODEChanging(value);
                this._LOTSIZECODE = value;
                this.OnLOTSIZECODEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LOTSIZECODE;
        partial void OnLOTSIZECODEChanging(string value);
        partial void OnLOTSIZECODEChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::SAPHana.Model.JCASVendorModel as global::SAPHana.Model.JCASVendorModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::SAPHana.Model.JCASVendorModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASVendorModel> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::SAPHana.Model.JCASVendorModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::SAPHana.Model.JCASVendorModel as global::SAPHana.Model.JCASVendorModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="jCASVendorId">The value of jCASVendorId</param>
        public static global::SAPHana.Model.JCASVendorModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASVendorModel> source,
            string jCASVendorId)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "JCASVendorId", jCASVendorId }
            };
            return new global::SAPHana.Model.JCASVendorModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::SAPHana.Model.JCASMPNModel as global::SAPHana.Model.JCASMPNModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::SAPHana.Model.JCASMPNModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASMPNModel> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::SAPHana.Model.JCASMPNModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::SAPHana.Model.JCASMPNModel as global::SAPHana.Model.JCASMPNModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="jCASMPNId">The value of jCASMPNId</param>
        public static global::SAPHana.Model.JCASMPNModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASMPNModel> source,
            string jCASMPNId)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "JCASMPNId", jCASMPNId }
            };
            return new global::SAPHana.Model.JCASMPNModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::SAPHana.Model.SitePartModel as global::SAPHana.Model.SitePartModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::SAPHana.Model.SitePartModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.SitePartModel> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::SAPHana.Model.SitePartModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::SAPHana.Model.SitePartModel as global::SAPHana.Model.SitePartModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="iD">The value of iD</param>
        public static global::SAPHana.Model.SitePartModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.SitePartModel> source,
            string iD)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ID", iD }
            };
            return new global::SAPHana.Model.SitePartModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for JCASVendor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASVendorModel> JCASVendor
        {
            get
            {
                if ((this._JCASVendor == null))
                {
                    this._JCASVendor = base.CreateQuery<global::SAPHana.Model.JCASVendorModel>("JCASVendor");
                }
                return this._JCASVendor;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASVendorModel> _JCASVendor;
        /// <summary>
        /// There are no comments for JCASMPN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASMPNModel> JCASMPN
        {
            get
            {
                if ((this._JCASMPN == null))
                {
                    this._JCASMPN = base.CreateQuery<global::SAPHana.Model.JCASMPNModel>("JCASMPN");
                }
                return this._JCASMPN;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.JCASMPNModel> _JCASMPN;
        /// <summary>
        /// There are no comments for SitePart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.SitePartModel> SitePart
        {
            get
            {
                if ((this._SitePart == null))
                {
                    this._SitePart = base.CreateQuery<global::SAPHana.Model.SitePartModel>("SitePart");
                }
                return this._SitePart;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::SAPHana.Model.SitePartModel> _SitePart;
        /// <summary>
        /// There are no comments for JCASVendor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToJCASVendor(global::SAPHana.Model.JCASVendorModel jCASVendorModel)
        {
            base.AddObject("JCASVendor", jCASVendorModel);
        }
        /// <summary>
        /// There are no comments for JCASMPN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToJCASMPN(global::SAPHana.Model.JCASMPNModel jCASMPNModel)
        {
            base.AddObject("JCASMPN", jCASMPNModel);
        }
        /// <summary>
        /// There are no comments for SitePart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSitePart(global::SAPHana.Model.SitePartModel sitePartModel)
        {
            base.AddObject("SitePart", sitePartModel);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"QSSODataServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
