//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/26/2022 11:32:03 AM
namespace production.pu.XS_PU_SAMPLESIZECALC
{
    
    /// <summary>
    /// There are no comments for XS_PU_SAMPLESIZECALC in the schema.
    /// </summary>
    public partial class XS_PU_SAMPLESIZECALC : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new XS_PU_SAMPLESIZECALC object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public XS_PU_SAMPLESIZECALC(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for SAMPLESIZECALC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SAMPLESIZECALCType> SAMPLESIZECALC
        {
            get
            {
                if ((this._SAMPLESIZECALC == null))
                {
                    this._SAMPLESIZECALC = base.CreateQuery<SAMPLESIZECALCType>("SAMPLESIZECALC");
                }
                return this._SAMPLESIZECALC;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SAMPLESIZECALCType> _SAMPLESIZECALC;
        /// <summary>
        /// There are no comments for InputParams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<InputParamsType> InputParams
        {
            get
            {
                if ((this._InputParams == null))
                {
                    this._InputParams = base.CreateQuery<InputParamsType>("InputParams");
                }
                return this._InputParams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<InputParamsType> _InputParams;
        /// <summary>
        /// There are no comments for SAMPLESIZECALC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSAMPLESIZECALC(SAMPLESIZECALCType sAMPLESIZECALCType)
        {
            base.AddObject("SAMPLESIZECALC", sAMPLESIZECALCType);
        }
        /// <summary>
        /// There are no comments for InputParams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInputParams(InputParamsType inputParamsType)
        {
            base.AddObject("InputParams", inputParamsType);
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_SAMPLESIZECALC.SAMPLESIZECALCType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SAMPLESIZECALC")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class SAMPLESIZECALCType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SAMPLESIZECALCType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SAMPLESIZECALCType CreateSAMPLESIZECALCType(string ID)
        {
            SAMPLESIZECALCType sAMPLESIZECALCType = new SAMPLESIZECALCType();
            sAMPLESIZECALCType.ID = ID;
            return sAMPLESIZECALCType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PART_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PART_NO
        {
            get
            {
                return this._PART_NO;
            }
            set
            {
                this.OnPART_NOChanging(value);
                this._PART_NO = value;
                this.OnPART_NOChanged();
                this.OnPropertyChanged("PART_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PART_NO;
        partial void OnPART_NOChanging(string value);
        partial void OnPART_NOChanged();
        /// <summary>
        /// There are no comments for Property PLAN_TYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PLAN_TYPE
        {
            get
            {
                return this._PLAN_TYPE;
            }
            set
            {
                this.OnPLAN_TYPEChanging(value);
                this._PLAN_TYPE = value;
                this.OnPLAN_TYPEChanged();
                this.OnPropertyChanged("PLAN_TYPE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PLAN_TYPE;
        partial void OnPLAN_TYPEChanging(string value);
        partial void OnPLAN_TYPEChanged();
        /// <summary>
        /// There are no comments for Property GRP_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GRP_NO
        {
            get
            {
                return this._GRP_NO;
            }
            set
            {
                this.OnGRP_NOChanging(value);
                this._GRP_NO = value;
                this.OnGRP_NOChanged();
                this.OnPropertyChanged("GRP_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GRP_NO;
        partial void OnGRP_NOChanging(string value);
        partial void OnGRP_NOChanged();
        /// <summary>
        /// There are no comments for Property GRP_COUNTER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GRP_COUNTER
        {
            get
            {
                return this._GRP_COUNTER;
            }
            set
            {
                this.OnGRP_COUNTERChanging(value);
                this._GRP_COUNTER = value;
                this.OnGRP_COUNTERChanged();
                this.OnPropertyChanged("GRP_COUNTER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GRP_COUNTER;
        partial void OnGRP_COUNTERChanging(string value);
        partial void OnGRP_COUNTERChanged();
        /// <summary>
        /// There are no comments for Property COUNTER_ADD in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COUNTER_ADD
        {
            get
            {
                return this._COUNTER_ADD;
            }
            set
            {
                this.OnCOUNTER_ADDChanging(value);
                this._COUNTER_ADD = value;
                this.OnCOUNTER_ADDChanged();
                this.OnPropertyChanged("COUNTER_ADD");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COUNTER_ADD;
        partial void OnCOUNTER_ADDChanging(string value);
        partial void OnCOUNTER_ADDChanged();
        /// <summary>
        /// There are no comments for Property COUNTER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COUNTER
        {
            get
            {
                return this._COUNTER;
            }
            set
            {
                this.OnCOUNTERChanging(value);
                this._COUNTER = value;
                this.OnCOUNTERChanged();
                this.OnPropertyChanged("COUNTER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COUNTER;
        partial void OnCOUNTERChanging(string value);
        partial void OnCOUNTERChanged();
        /// <summary>
        /// There are no comments for Property SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SITE
        {
            get
            {
                return this._SITE;
            }
            set
            {
                this.OnSITEChanging(value);
                this._SITE = value;
                this.OnSITEChanged();
                this.OnPropertyChanged("SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SITE;
        partial void OnSITEChanging(string value);
        partial void OnSITEChanged();
        /// <summary>
        /// There are no comments for Property QDMR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QDMR
        {
            get
            {
                return this._QDMR;
            }
            set
            {
                this.OnQDMRChanging(value);
                this._QDMR = value;
                this.OnQDMRChanged();
                this.OnPropertyChanged("QDMR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QDMR;
        partial void OnQDMRChanging(string value);
        partial void OnQDMRChanged();
        /// <summary>
        /// There are no comments for Property DMR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DMR
        {
            get
            {
                return this._DMR;
            }
            set
            {
                this.OnDMRChanging(value);
                this._DMR = value;
                this.OnDMRChanged();
                this.OnPropertyChanged("DMR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DMR;
        partial void OnDMRChanging(string value);
        partial void OnDMRChanged();
        /// <summary>
        /// There are no comments for Property SMPL_PROC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SMPL_PROC
        {
            get
            {
                return this._SMPL_PROC;
            }
            set
            {
                this.OnSMPL_PROCChanging(value);
                this._SMPL_PROC = value;
                this.OnSMPL_PROCChanged();
                this.OnPropertyChanged("SMPL_PROC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SMPL_PROC;
        partial void OnSMPL_PROCChanging(string value);
        partial void OnSMPL_PROCChanged();
        /// <summary>
        /// There are no comments for Property DELETE_IND in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DELETE_IND
        {
            get
            {
                return this._DELETE_IND;
            }
            set
            {
                this.OnDELETE_INDChanging(value);
                this._DELETE_IND = value;
                this.OnDELETE_INDChanged();
                this.OnPropertyChanged("DELETE_IND");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DELETE_IND;
        partial void OnDELETE_INDChanging(string value);
        partial void OnDELETE_INDChanged();
        /// <summary>
        /// There are no comments for Property INSP_CHAR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSP_CHAR
        {
            get
            {
                return this._INSP_CHAR;
            }
            set
            {
                this.OnINSP_CHARChanging(value);
                this._INSP_CHAR = value;
                this.OnINSP_CHARChanged();
                this.OnPropertyChanged("INSP_CHAR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSP_CHAR;
        partial void OnINSP_CHARChanging(string value);
        partial void OnINSP_CHARChanged();
        /// <summary>
        /// There are no comments for Property INSP_METHOD in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSP_METHOD
        {
            get
            {
                return this._INSP_METHOD;
            }
            set
            {
                this.OnINSP_METHODChanging(value);
                this._INSP_METHOD = value;
                this.OnINSP_METHODChanged();
                this.OnPropertyChanged("INSP_METHOD");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSP_METHOD;
        partial void OnINSP_METHODChanging(string value);
        partial void OnINSP_METHODChanged();
        /// <summary>
        /// There are no comments for Property METHOD_VER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string METHOD_VER
        {
            get
            {
                return this._METHOD_VER;
            }
            set
            {
                this.OnMETHOD_VERChanging(value);
                this._METHOD_VER = value;
                this.OnMETHOD_VERChanged();
                this.OnPropertyChanged("METHOD_VER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _METHOD_VER;
        partial void OnMETHOD_VERChanging(string value);
        partial void OnMETHOD_VERChanged();
        /// <summary>
        /// There are no comments for Property METHOD_SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string METHOD_SITE
        {
            get
            {
                return this._METHOD_SITE;
            }
            set
            {
                this.OnMETHOD_SITEChanging(value);
                this._METHOD_SITE = value;
                this.OnMETHOD_SITEChanged();
                this.OnPropertyChanged("METHOD_SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _METHOD_SITE;
        partial void OnMETHOD_SITEChanging(string value);
        partial void OnMETHOD_SITEChanged();
        /// <summary>
        /// There are no comments for Property MSTR_INSP_CHAR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MSTR_INSP_CHAR
        {
            get
            {
                return this._MSTR_INSP_CHAR;
            }
            set
            {
                this.OnMSTR_INSP_CHARChanging(value);
                this._MSTR_INSP_CHAR = value;
                this.OnMSTR_INSP_CHARChanged();
                this.OnPropertyChanged("MSTR_INSP_CHAR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MSTR_INSP_CHAR;
        partial void OnMSTR_INSP_CHARChanging(string value);
        partial void OnMSTR_INSP_CHARChanged();
        /// <summary>
        /// There are no comments for Property MSTR_VER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MSTR_VER
        {
            get
            {
                return this._MSTR_VER;
            }
            set
            {
                this.OnMSTR_VERChanging(value);
                this._MSTR_VER = value;
                this.OnMSTR_VERChanged();
                this.OnPropertyChanged("MSTR_VER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MSTR_VER;
        partial void OnMSTR_VERChanging(string value);
        partial void OnMSTR_VERChanged();
        /// <summary>
        /// There are no comments for Property SMPL_SIZE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SMPL_SIZE
        {
            get
            {
                return this._SMPL_SIZE;
            }
            set
            {
                this.OnSMPL_SIZEChanging(value);
                this._SMPL_SIZE = value;
                this.OnSMPL_SIZEChanged();
                this.OnPropertyChanged("SMPL_SIZE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SMPL_SIZE;
        partial void OnSMPL_SIZEChanging(string value);
        partial void OnSMPL_SIZEChanged();
        /// <summary>
        /// There are no comments for Property SMPL_TYPE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SMPL_TYPE
        {
            get
            {
                return this._SMPL_TYPE;
            }
            set
            {
                this.OnSMPL_TYPEChanging(value);
                this._SMPL_TYPE = value;
                this.OnSMPL_TYPEChanged();
                this.OnPropertyChanged("SMPL_TYPE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SMPL_TYPE;
        partial void OnSMPL_TYPEChanging(string value);
        partial void OnSMPL_TYPEChanged();
        /// <summary>
        /// There are no comments for Property VALUATION_MODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VALUATION_MODE
        {
            get
            {
                return this._VALUATION_MODE;
            }
            set
            {
                this.OnVALUATION_MODEChanging(value);
                this._VALUATION_MODE = value;
                this.OnVALUATION_MODEChanged();
                this.OnPropertyChanged("VALUATION_MODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VALUATION_MODE;
        partial void OnVALUATION_MODEChanging(string value);
        partial void OnVALUATION_MODEChanged();
        /// <summary>
        /// There are no comments for Property SMPL_SCHEME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SMPL_SCHEME
        {
            get
            {
                return this._SMPL_SCHEME;
            }
            set
            {
                this.OnSMPL_SCHEMEChanging(value);
                this._SMPL_SCHEME = value;
                this.OnSMPL_SCHEMEChanged();
                this.OnPropertyChanged("SMPL_SCHEME");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SMPL_SCHEME;
        partial void OnSMPL_SCHEMEChanging(string value);
        partial void OnSMPL_SCHEMEChanged();
        /// <summary>
        /// There are no comments for Property INSP_SEV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSP_SEV
        {
            get
            {
                return this._INSP_SEV;
            }
            set
            {
                this.OnINSP_SEVChanging(value);
                this._INSP_SEV = value;
                this.OnINSP_SEVChanged();
                this.OnPropertyChanged("INSP_SEV");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSP_SEV;
        partial void OnINSP_SEVChanging(string value);
        partial void OnINSP_SEVChanged();
        /// <summary>
        /// There are no comments for Property NO_USE_IP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NO_USE_IP
        {
            get
            {
                return this._NO_USE_IP;
            }
            set
            {
                this.OnNO_USE_IPChanging(value);
                this._NO_USE_IP = value;
                this.OnNO_USE_IPChanged();
                this.OnPropertyChanged("NO_USE_IP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NO_USE_IP;
        partial void OnNO_USE_IPChanging(string value);
        partial void OnNO_USE_IPChanged();
        /// <summary>
        /// There are no comments for Property USE_IP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string USE_IP
        {
            get
            {
                return this._USE_IP;
            }
            set
            {
                this.OnUSE_IPChanging(value);
                this._USE_IP = value;
                this.OnUSE_IPChanged();
                this.OnPropertyChanged("USE_IP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _USE_IP;
        partial void OnUSE_IPChanging(string value);
        partial void OnUSE_IPChanged();
        /// <summary>
        /// There are no comments for Property DETERMINE_KEY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DETERMINE_KEY
        {
            get
            {
                return this._DETERMINE_KEY;
            }
            set
            {
                this.OnDETERMINE_KEYChanging(value);
                this._DETERMINE_KEY = value;
                this.OnDETERMINE_KEYChanged();
                this.OnPropertyChanged("DETERMINE_KEY");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DETERMINE_KEY;
        partial void OnDETERMINE_KEYChanging(string value);
        partial void OnDETERMINE_KEYChanged();
        /// <summary>
        /// There are no comments for Property QD_SHORT_TEXT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QD_SHORT_TEXT
        {
            get
            {
                return this._QD_SHORT_TEXT;
            }
            set
            {
                this.OnQD_SHORT_TEXTChanging(value);
                this._QD_SHORT_TEXT = value;
                this.OnQD_SHORT_TEXTChanged();
                this.OnPropertyChanged("QD_SHORT_TEXT");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QD_SHORT_TEXT;
        partial void OnQD_SHORT_TEXTChanging(string value);
        partial void OnQD_SHORT_TEXTChanged();
        /// <summary>
        /// There are no comments for Property CREATED_ON in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CREATED_ON
        {
            get
            {
                return this._CREATED_ON;
            }
            set
            {
                this.OnCREATED_ONChanging(value);
                this._CREATED_ON = value;
                this.OnCREATED_ONChanged();
                this.OnPropertyChanged("CREATED_ON");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CREATED_ON;
        partial void OnCREATED_ONChanging(string value);
        partial void OnCREATED_ONChanged();
        /// <summary>
        /// There are no comments for Property CHANGED_ON in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CHANGED_ON
        {
            get
            {
                return this._CHANGED_ON;
            }
            set
            {
                this.OnCHANGED_ONChanging(value);
                this._CHANGED_ON = value;
                this.OnCHANGED_ONChanged();
                this.OnPropertyChanged("CHANGED_ON");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CHANGED_ON;
        partial void OnCHANGED_ONChanging(string value);
        partial void OnCHANGED_ONChanged();
        /// <summary>
        /// There are no comments for Property SEQ_CTR_IT_SCHEME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SEQ_CTR_IT_SCHEME
        {
            get
            {
                return this._SEQ_CTR_IT_SCHEME;
            }
            set
            {
                this.OnSEQ_CTR_IT_SCHEMEChanging(value);
                this._SEQ_CTR_IT_SCHEME = value;
                this.OnSEQ_CTR_IT_SCHEMEChanged();
                this.OnPropertyChanged("SEQ_CTR_IT_SCHEME");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SEQ_CTR_IT_SCHEME;
        partial void OnSEQ_CTR_IT_SCHEMEChanging(string value);
        partial void OnSEQ_CTR_IT_SCHEMEChanged();
        /// <summary>
        /// There are no comments for Property SEQ_CTR_SI_SCHEME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SEQ_CTR_SI_SCHEME
        {
            get
            {
                return this._SEQ_CTR_SI_SCHEME;
            }
            set
            {
                this.OnSEQ_CTR_SI_SCHEMEChanging(value);
                this._SEQ_CTR_SI_SCHEME = value;
                this.OnSEQ_CTR_SI_SCHEMEChanged();
                this.OnPropertyChanged("SEQ_CTR_SI_SCHEME");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SEQ_CTR_SI_SCHEME;
        partial void OnSEQ_CTR_SI_SCHEMEChanging(string value);
        partial void OnSEQ_CTR_SI_SCHEMEChanged();
        /// <summary>
        /// There are no comments for Property NO_SMPL_SIZE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NO_SMPL_SIZE
        {
            get
            {
                return this._NO_SMPL_SIZE;
            }
            set
            {
                this.OnNO_SMPL_SIZEChanging(value);
                this._NO_SMPL_SIZE = value;
                this.OnNO_SMPL_SIZEChanged();
                this.OnPropertyChanged("NO_SMPL_SIZE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NO_SMPL_SIZE;
        partial void OnNO_SMPL_SIZEChanging(string value);
        partial void OnNO_SMPL_SIZEChanged();
        /// <summary>
        /// There are no comments for Property LOT_SIZE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LOT_SIZE
        {
            get
            {
                return this._LOT_SIZE;
            }
            set
            {
                this.OnLOT_SIZEChanging(value);
                this._LOT_SIZE = value;
                this.OnLOT_SIZEChanged();
                this.OnPropertyChanged("LOT_SIZE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LOT_SIZE;
        partial void OnLOT_SIZEChanging(string value);
        partial void OnLOT_SIZEChanged();
        /// <summary>
        /// There are no comments for Property ACPT_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ACPT_NO
        {
            get
            {
                return this._ACPT_NO;
            }
            set
            {
                this.OnACPT_NOChanging(value);
                this._ACPT_NO = value;
                this.OnACPT_NOChanged();
                this.OnPropertyChanged("ACPT_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ACPT_NO;
        partial void OnACPT_NOChanging(string value);
        partial void OnACPT_NOChanged();
        /// <summary>
        /// There are no comments for Property REJ_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string REJ_NO
        {
            get
            {
                return this._REJ_NO;
            }
            set
            {
                this.OnREJ_NOChanging(value);
                this._REJ_NO = value;
                this.OnREJ_NOChanged();
                this.OnPropertyChanged("REJ_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _REJ_NO;
        partial void OnREJ_NOChanging(string value);
        partial void OnREJ_NOChanged();
        /// <summary>
        /// There are no comments for Property QDPA_INSP_SEV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QDPA_INSP_SEV
        {
            get
            {
                return this._QDPA_INSP_SEV;
            }
            set
            {
                this.OnQDPA_INSP_SEVChanging(value);
                this._QDPA_INSP_SEV = value;
                this.OnQDPA_INSP_SEVChanged();
                this.OnPropertyChanged("QDPA_INSP_SEV");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QDPA_INSP_SEV;
        partial void OnQDPA_INSP_SEVChanging(string value);
        partial void OnQDPA_INSP_SEVChanged();
        /// <summary>
        /// There are no comments for Property QDPS_INSP_SEV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QDPS_INSP_SEV
        {
            get
            {
                return this._QDPS_INSP_SEV;
            }
            set
            {
                this.OnQDPS_INSP_SEVChanging(value);
                this._QDPS_INSP_SEV = value;
                this.OnQDPS_INSP_SEVChanged();
                this.OnPropertyChanged("QDPS_INSP_SEV");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QDPS_INSP_SEV;
        partial void OnQDPS_INSP_SEVChanging(string value);
        partial void OnQDPS_INSP_SEVChanged();
        /// <summary>
        /// There are no comments for Property INSP_STAGE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INSP_STAGE
        {
            get
            {
                return this._INSP_STAGE;
            }
            set
            {
                this.OnINSP_STAGEChanging(value);
                this._INSP_STAGE = value;
                this.OnINSP_STAGEChanged();
                this.OnPropertyChanged("INSP_STAGE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INSP_STAGE;
        partial void OnINSP_STAGEChanging(string value);
        partial void OnINSP_STAGEChanged();
        /// <summary>
        /// There are no comments for Property NEW_INSP_STG_OK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NEW_INSP_STG_OK
        {
            get
            {
                return this._NEW_INSP_STG_OK;
            }
            set
            {
                this.OnNEW_INSP_STG_OKChanging(value);
                this._NEW_INSP_STG_OK = value;
                this.OnNEW_INSP_STG_OKChanged();
                this.OnPropertyChanged("NEW_INSP_STG_OK");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NEW_INSP_STG_OK;
        partial void OnNEW_INSP_STG_OKChanging(string value);
        partial void OnNEW_INSP_STG_OKChanged();
        /// <summary>
        /// There are no comments for Property NEW_INSP_STG_NOK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NEW_INSP_STG_NOK
        {
            get
            {
                return this._NEW_INSP_STG_NOK;
            }
            set
            {
                this.OnNEW_INSP_STG_NOKChanging(value);
                this._NEW_INSP_STG_NOK = value;
                this.OnNEW_INSP_STG_NOKChanged();
                this.OnPropertyChanged("NEW_INSP_STG_NOK");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NEW_INSP_STG_NOK;
        partial void OnNEW_INSP_STG_NOKChanging(string value);
        partial void OnNEW_INSP_STG_NOKChanged();
        /// <summary>
        /// There are no comments for Property QDDR_DMR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QDDR_DMR
        {
            get
            {
                return this._QDDR_DMR;
            }
            set
            {
                this.OnQDDR_DMRChanging(value);
                this._QDDR_DMR = value;
                this.OnQDDR_DMRChanged();
                this.OnPropertyChanged("QDDR_DMR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QDDR_DMR;
        partial void OnQDDR_DMRChanging(string value);
        partial void OnQDDR_DMRChanged();
        /// <summary>
        /// There are no comments for Property INIT_INSP_STAGE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string INIT_INSP_STAGE
        {
            get
            {
                return this._INIT_INSP_STAGE;
            }
            set
            {
                this.OnINIT_INSP_STAGEChanging(value);
                this._INIT_INSP_STAGE = value;
                this.OnINIT_INSP_STAGEChanged();
                this.OnPropertyChanged("INIT_INSP_STAGE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _INIT_INSP_STAGE;
        partial void OnINIT_INSP_STAGEChanging(string value);
        partial void OnINIT_INSP_STAGEChanged();
        /// <summary>
        /// There are no comments for Property QDQL_SEQ_CTR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QDQL_SEQ_CTR
        {
            get
            {
                return this._QDQL_SEQ_CTR;
            }
            set
            {
                this.OnQDQL_SEQ_CTRChanging(value);
                this._QDQL_SEQ_CTR = value;
                this.OnQDQL_SEQ_CTRChanged();
                this.OnPropertyChanged("QDQL_SEQ_CTR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QDQL_SEQ_CTR;
        partial void OnQDQL_SEQ_CTRChanging(string value);
        partial void OnQDQL_SEQ_CTRChanged();
        /// <summary>
        /// There are no comments for Property QDQL_DMR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QDQL_DMR
        {
            get
            {
                return this._QDQL_DMR;
            }
            set
            {
                this.OnQDQL_DMRChanging(value);
                this._QDQL_DMR = value;
                this.OnQDQL_DMRChanged();
                this.OnPropertyChanged("QDQL_DMR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QDQL_DMR;
        partial void OnQDQL_DMRChanging(string value);
        partial void OnQDQL_DMRChanged();
        /// <summary>
        /// There are no comments for Property NEXT_INSP_STAGE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NEXT_INSP_STAGE
        {
            get
            {
                return this._NEXT_INSP_STAGE;
            }
            set
            {
                this.OnNEXT_INSP_STAGEChanging(value);
                this._NEXT_INSP_STAGE = value;
                this.OnNEXT_INSP_STAGEChanged();
                this.OnPropertyChanged("NEXT_INSP_STAGE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NEXT_INSP_STAGE;
        partial void OnNEXT_INSP_STAGEChanging(string value);
        partial void OnNEXT_INSP_STAGEChanged();
        /// <summary>
        /// There are no comments for Property VENDOR_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_CODE
        {
            get
            {
                return this._VENDOR_CODE;
            }
            set
            {
                this.OnVENDOR_CODEChanging(value);
                this._VENDOR_CODE = value;
                this.OnVENDOR_CODEChanged();
                this.OnPropertyChanged("VENDOR_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_CODE;
        partial void OnVENDOR_CODEChanging(string value);
        partial void OnVENDOR_CODEChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_SAMPLESIZECALC.InputParamsType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IP_SITE
    /// IP_PARTNO
    /// IP_VENDOR
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("InputParams")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IP_SITE", "IP_PARTNO", "IP_VENDOR")]
    public partial class InputParamsType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property IP_SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IP_SITE
        {
            get
            {
                return this._IP_SITE;
            }
            set
            {
                this.OnIP_SITEChanging(value);
                this._IP_SITE = value;
                this.OnIP_SITEChanged();
                this.OnPropertyChanged("IP_SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IP_SITE = "CN02";
        partial void OnIP_SITEChanging(string value);
        partial void OnIP_SITEChanged();
        /// <summary>
        /// There are no comments for Property IP_PARTNO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IP_PARTNO
        {
            get
            {
                return this._IP_PARTNO;
            }
            set
            {
                this.OnIP_PARTNOChanging(value);
                this._IP_PARTNO = value;
                this.OnIP_PARTNOChanged();
                this.OnPropertyChanged("IP_PARTNO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IP_PARTNO = "~PartNumber1~PartNumber2~PartNumberN~";
        partial void OnIP_PARTNOChanging(string value);
        partial void OnIP_PARTNOChanged();
        /// <summary>
        /// There are no comments for Property IP_VENDOR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IP_VENDOR
        {
            get
            {
                return this._IP_VENDOR;
            }
            set
            {
                this.OnIP_VENDORChanging(value);
                this._IP_VENDOR = value;
                this.OnIP_VENDORChanged();
                this.OnPropertyChanged("IP_VENDOR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IP_VENDOR = "VendorCode";
        partial void OnIP_VENDORChanging(string value);
        partial void OnIP_VENDORChanged();
        /// <summary>
        /// There are no comments for SAMPLESIZECALC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SAMPLESIZECALCType> SAMPLESIZECALC
        {
            get
            {
                return this._SAMPLESIZECALC;
            }
            set
            {
                this._SAMPLESIZECALC = value;
                this.OnPropertyChanged("SAMPLESIZECALC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SAMPLESIZECALCType> _SAMPLESIZECALC = new global::System.Data.Services.Client.DataServiceCollection<SAMPLESIZECALCType>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
