//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/14/2021 3:03:24 PM
namespace Reference
{
    
    /// <summary>
    /// There are no comments for XS_PU_PARTNUMBER_SITE_MANUF in the schema.
    /// </summary>
    public partial class XS_PU_PARTNUMBER_SITE_MANUF : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new XS_PU_PARTNUMBER_SITE_MANUF object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public XS_PU_PARTNUMBER_SITE_MANUF(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "production.pu.XS_PU_PARTNUMBER_SITE_MANUF", "Reference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Reference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("production.pu.XS_PU_PARTNUMBER_SITE_MANUF.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for PARTNUMBER_BY_SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PARTNUMBER_BY_SITEType> PARTNUMBER_BY_SITE
        {
            get
            {
                if ((this._PARTNUMBER_BY_SITE == null))
                {
                    this._PARTNUMBER_BY_SITE = base.CreateQuery<PARTNUMBER_BY_SITEType>("PARTNUMBER_BY_SITE");
                }
                return this._PARTNUMBER_BY_SITE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PARTNUMBER_BY_SITEType> _PARTNUMBER_BY_SITE;
        /// <summary>
        /// There are no comments for PARTNUMBER_BY_SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPARTNUMBER_BY_SITE(PARTNUMBER_BY_SITEType pARTNUMBER_BY_SITEType)
        {
            base.AddObject("PARTNUMBER_BY_SITE", pARTNUMBER_BY_SITEType);
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_PARTNUMBER_SITE_MANUF.PARTNUMBER_BY_SITEType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PARTNUMBER_BY_SITE")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class PARTNUMBER_BY_SITEType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PARTNUMBER_BY_SITEType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PARTNUMBER_BY_SITEType CreatePARTNUMBER_BY_SITEType(string ID)
        {
            PARTNUMBER_BY_SITEType pARTNUMBER_BY_SITEType = new PARTNUMBER_BY_SITEType();
            pARTNUMBER_BY_SITEType.ID = ID;
            return pARTNUMBER_BY_SITEType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SITE
        {
            get
            {
                return this._SITE;
            }
            set
            {
                this.OnSITEChanging(value);
                this._SITE = value;
                this.OnSITEChanged();
                this.OnPropertyChanged("SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SITE;
        partial void OnSITEChanging(string value);
        partial void OnSITEChanged();
        /// <summary>
        /// There are no comments for Property JABIL_PART_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string JABIL_PART_NO
        {
            get
            {
                return this._JABIL_PART_NO;
            }
            set
            {
                this.OnJABIL_PART_NOChanging(value);
                this._JABIL_PART_NO = value;
                this.OnJABIL_PART_NOChanged();
                this.OnPropertyChanged("JABIL_PART_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _JABIL_PART_NO;
        partial void OnJABIL_PART_NOChanging(string value);
        partial void OnJABIL_PART_NOChanged();
        /// <summary>
        /// There are no comments for Property MPN_MTRL_HERS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MPN_MTRL_HERS
        {
            get
            {
                return this._MPN_MTRL_HERS;
            }
            set
            {
                this.OnMPN_MTRL_HERSChanging(value);
                this._MPN_MTRL_HERS = value;
                this.OnMPN_MTRL_HERSChanged();
                this.OnPropertyChanged("MPN_MTRL_HERS");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MPN_MTRL_HERS;
        partial void OnMPN_MTRL_HERSChanging(string value);
        partial void OnMPN_MTRL_HERSChanged();
        /// <summary>
        /// There are no comments for Property MANUFACTURER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MANUFACTURER
        {
            get
            {
                return this._MANUFACTURER;
            }
            set
            {
                this.OnMANUFACTURERChanging(value);
                this._MANUFACTURER = value;
                this.OnMANUFACTURERChanged();
                this.OnPropertyChanged("MANUFACTURER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MANUFACTURER;
        partial void OnMANUFACTURERChanging(string value);
        partial void OnMANUFACTURERChanged();
        /// <summary>
        /// There are no comments for Property PART_VALID_FROM in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PART_VALID_FROM
        {
            get
            {
                return this._PART_VALID_FROM;
            }
            set
            {
                this.OnPART_VALID_FROMChanging(value);
                this._PART_VALID_FROM = value;
                this.OnPART_VALID_FROMChanged();
                this.OnPropertyChanged("PART_VALID_FROM");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PART_VALID_FROM;
        partial void OnPART_VALID_FROMChanging(string value);
        partial void OnPART_VALID_FROMChanged();
        /// <summary>
        /// There are no comments for Property PART_VALID_TO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PART_VALID_TO
        {
            get
            {
                return this._PART_VALID_TO;
            }
            set
            {
                this.OnPART_VALID_TOChanging(value);
                this._PART_VALID_TO = value;
                this.OnPART_VALID_TOChanged();
                this.OnPropertyChanged("PART_VALID_TO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PART_VALID_TO;
        partial void OnPART_VALID_TOChanging(string value);
        partial void OnPART_VALID_TOChanged();
        /// <summary>
        /// There are no comments for Property MEDIACODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MEDIACODE
        {
            get
            {
                return this._MEDIACODE;
            }
            set
            {
                this.OnMEDIACODEChanging(value);
                this._MEDIACODE = value;
                this.OnMEDIACODEChanged();
                this.OnPropertyChanged("MEDIACODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MEDIACODE;
        partial void OnMEDIACODEChanging(string value);
        partial void OnMEDIACODEChanged();
        /// <summary>
        /// There are no comments for Property MANUF_PART_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MANUF_PART_NO
        {
            get
            {
                return this._MANUF_PART_NO;
            }
            set
            {
                this.OnMANUF_PART_NOChanging(value);
                this._MANUF_PART_NO = value;
                this.OnMANUF_PART_NOChanged();
                this.OnPropertyChanged("MANUF_PART_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MANUF_PART_NO;
        partial void OnMANUF_PART_NOChanging(string value);
        partial void OnMANUF_PART_NOChanged();
        /// <summary>
        /// There are no comments for Property MASKED_MPN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MASKED_MPN
        {
            get
            {
                return this._MASKED_MPN;
            }
            set
            {
                this.OnMASKED_MPNChanging(value);
                this._MASKED_MPN = value;
                this.OnMASKED_MPNChanged();
                this.OnPropertyChanged("MASKED_MPN");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MASKED_MPN;
        partial void OnMASKED_MPNChanging(string value);
        partial void OnMASKED_MPNChanged();
        /// <summary>
        /// There are no comments for Property MATERIAL_DESC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MATERIAL_DESC
        {
            get
            {
                return this._MATERIAL_DESC;
            }
            set
            {
                this.OnMATERIAL_DESCChanging(value);
                this._MATERIAL_DESC = value;
                this.OnMATERIAL_DESCChanged();
                this.OnPropertyChanged("MATERIAL_DESC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MATERIAL_DESC;
        partial void OnMATERIAL_DESCChanging(string value);
        partial void OnMATERIAL_DESCChanged();
        /// <summary>
        /// There are no comments for Property JABIL_OWNER_CONTACT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string JABIL_OWNER_CONTACT
        {
            get
            {
                return this._JABIL_OWNER_CONTACT;
            }
            set
            {
                this.OnJABIL_OWNER_CONTACTChanging(value);
                this._JABIL_OWNER_CONTACT = value;
                this.OnJABIL_OWNER_CONTACTChanged();
                this.OnPropertyChanged("JABIL_OWNER_CONTACT");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _JABIL_OWNER_CONTACT;
        partial void OnJABIL_OWNER_CONTACTChanging(string value);
        partial void OnJABIL_OWNER_CONTACTChanged();
        /// <summary>
        /// There are no comments for Property MATERIAL_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MATERIAL_GROUP
        {
            get
            {
                return this._MATERIAL_GROUP;
            }
            set
            {
                this.OnMATERIAL_GROUPChanging(value);
                this._MATERIAL_GROUP = value;
                this.OnMATERIAL_GROUPChanged();
                this.OnPropertyChanged("MATERIAL_GROUP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MATERIAL_GROUP;
        partial void OnMATERIAL_GROUPChanging(string value);
        partial void OnMATERIAL_GROUPChanged();
        /// <summary>
        /// There are no comments for Property CREATED_DATE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CREATED_DATE
        {
            get
            {
                return this._CREATED_DATE;
            }
            set
            {
                this.OnCREATED_DATEChanging(value);
                this._CREATED_DATE = value;
                this.OnCREATED_DATEChanged();
                this.OnPropertyChanged("CREATED_DATE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CREATED_DATE;
        partial void OnCREATED_DATEChanging(string value);
        partial void OnCREATED_DATEChanged();
        /// <summary>
        /// There are no comments for Property LAST_MODIFIED_DATE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LAST_MODIFIED_DATE
        {
            get
            {
                return this._LAST_MODIFIED_DATE;
            }
            set
            {
                this.OnLAST_MODIFIED_DATEChanging(value);
                this._LAST_MODIFIED_DATE = value;
                this.OnLAST_MODIFIED_DATEChanged();
                this.OnPropertyChanged("LAST_MODIFIED_DATE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LAST_MODIFIED_DATE;
        partial void OnLAST_MODIFIED_DATEChanging(string value);
        partial void OnLAST_MODIFIED_DATEChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
