//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/10/2021 6:58:42 PM
namespace production.pu.XS_PU_EIQC_PO
{
    
    /// <summary>
    /// There are no comments for XS_PU_EIQC_PO in the schema.
    /// </summary>
    public partial class XS_PU_EIQC_PO : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new XS_PU_EIQC_PO object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public XS_PU_EIQC_PO(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for PO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<POType> PO
        {
            get
            {
                if ((this._PO == null))
                {
                    this._PO = base.CreateQuery<POType>("PO");
                }
                return this._PO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<POType> _PO;
        /// <summary>
        /// There are no comments for PO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPO(POType pOType)
        {
            base.AddObject("PO", pOType);
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_EIQC_PO.POType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PO")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class POType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new POType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static POType CreatePOType(string ID)
        {
            POType pOType = new POType();
            pOType.ID = ID;
            return pOType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SITE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SITE
        {
            get
            {
                return this._SITE;
            }
            set
            {
                this.OnSITEChanging(value);
                this._SITE = value;
                this.OnSITEChanged();
                this.OnPropertyChanged("SITE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SITE;
        partial void OnSITEChanging(string value);
        partial void OnSITEChanged();
        /// <summary>
        /// There are no comments for Property PART_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PART_NO
        {
            get
            {
                return this._PART_NO;
            }
            set
            {
                this.OnPART_NOChanging(value);
                this._PART_NO = value;
                this.OnPART_NOChanged();
                this.OnPropertyChanged("PART_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PART_NO;
        partial void OnPART_NOChanging(string value);
        partial void OnPART_NOChanged();
        /// <summary>
        /// There are no comments for Property MPN_MATERIAL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MPN_MATERIAL
        {
            get
            {
                return this._MPN_MATERIAL;
            }
            set
            {
                this.OnMPN_MATERIALChanging(value);
                this._MPN_MATERIAL = value;
                this.OnMPN_MATERIALChanged();
                this.OnPropertyChanged("MPN_MATERIAL");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MPN_MATERIAL;
        partial void OnMPN_MATERIALChanging(string value);
        partial void OnMPN_MATERIALChanged();
        /// <summary>
        /// There are no comments for Property CREATED_DATE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CREATED_DATE
        {
            get
            {
                return this._CREATED_DATE;
            }
            set
            {
                this.OnCREATED_DATEChanging(value);
                this._CREATED_DATE = value;
                this.OnCREATED_DATEChanged();
                this.OnPropertyChanged("CREATED_DATE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CREATED_DATE;
        partial void OnCREATED_DATEChanging(string value);
        partial void OnCREATED_DATEChanged();
        /// <summary>
        /// There are no comments for Property PO_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PO_NO
        {
            get
            {
                return this._PO_NO;
            }
            set
            {
                this.OnPO_NOChanging(value);
                this._PO_NO = value;
                this.OnPO_NOChanged();
                this.OnPropertyChanged("PO_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PO_NO;
        partial void OnPO_NOChanging(string value);
        partial void OnPO_NOChanged();
        /// <summary>
        /// There are no comments for Property PO_LINE_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PO_LINE_NO
        {
            get
            {
                return this._PO_LINE_NO;
            }
            set
            {
                this.OnPO_LINE_NOChanging(value);
                this._PO_LINE_NO = value;
                this.OnPO_LINE_NOChanged();
                this.OnPropertyChanged("PO_LINE_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PO_LINE_NO;
        partial void OnPO_LINE_NOChanging(string value);
        partial void OnPO_LINE_NOChanged();
        /// <summary>
        /// There are no comments for Property QUANTITY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> QUANTITY
        {
            get
            {
                return this._QUANTITY;
            }
            set
            {
                this.OnQUANTITYChanging(value);
                this._QUANTITY = value;
                this.OnQUANTITYChanged();
                this.OnPropertyChanged("QUANTITY");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _QUANTITY;
        partial void OnQUANTITYChanging(global::System.Nullable<decimal> value);
        partial void OnQUANTITYChanged();
        /// <summary>
        /// There are no comments for Property VENDOR_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VENDOR_CODE
        {
            get
            {
                return this._VENDOR_CODE;
            }
            set
            {
                this.OnVENDOR_CODEChanging(value);
                this._VENDOR_CODE = value;
                this.OnVENDOR_CODEChanged();
                this.OnPropertyChanged("VENDOR_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VENDOR_CODE;
        partial void OnVENDOR_CODEChanging(string value);
        partial void OnVENDOR_CODEChanged();
        /// <summary>
        /// There are no comments for Property MANUFACTURER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MANUFACTURER
        {
            get
            {
                return this._MANUFACTURER;
            }
            set
            {
                this.OnMANUFACTURERChanging(value);
                this._MANUFACTURER = value;
                this.OnMANUFACTURERChanged();
                this.OnPropertyChanged("MANUFACTURER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MANUFACTURER;
        partial void OnMANUFACTURERChanging(string value);
        partial void OnMANUFACTURERChanged();
        /// <summary>
        /// There are no comments for Property MANUF_PART_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MANUF_PART_NO
        {
            get
            {
                return this._MANUF_PART_NO;
            }
            set
            {
                this.OnMANUF_PART_NOChanging(value);
                this._MANUF_PART_NO = value;
                this.OnMANUF_PART_NOChanged();
                this.OnPropertyChanged("MANUF_PART_NO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MANUF_PART_NO;
        partial void OnMANUF_PART_NOChanging(string value);
        partial void OnMANUF_PART_NOChanged();
        /// <summary>
        /// There are no comments for Property PURCHASE_ORG in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PURCHASE_ORG
        {
            get
            {
                return this._PURCHASE_ORG;
            }
            set
            {
                this.OnPURCHASE_ORGChanging(value);
                this._PURCHASE_ORG = value;
                this.OnPURCHASE_ORGChanged();
                this.OnPropertyChanged("PURCHASE_ORG");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PURCHASE_ORG;
        partial void OnPURCHASE_ORGChanging(string value);
        partial void OnPURCHASE_ORGChanged();
        /// <summary>
        /// There are no comments for Property PURCHASE_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PURCHASE_GROUP
        {
            get
            {
                return this._PURCHASE_GROUP;
            }
            set
            {
                this.OnPURCHASE_GROUPChanging(value);
                this._PURCHASE_GROUP = value;
                this.OnPURCHASE_GROUPChanged();
                this.OnPropertyChanged("PURCHASE_GROUP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PURCHASE_GROUP;
        partial void OnPURCHASE_GROUPChanging(string value);
        partial void OnPURCHASE_GROUPChanged();
        /// <summary>
        /// There are no comments for Property COMPANY_CODE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMPANY_CODE
        {
            get
            {
                return this._COMPANY_CODE;
            }
            set
            {
                this.OnCOMPANY_CODEChanging(value);
                this._COMPANY_CODE = value;
                this.OnCOMPANY_CODEChanged();
                this.OnPropertyChanged("COMPANY_CODE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMPANY_CODE;
        partial void OnCOMPANY_CODEChanging(string value);
        partial void OnCOMPANY_CODEChanged();
        /// <summary>
        /// There are no comments for Property STATUS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string STATUS
        {
            get
            {
                return this._STATUS;
            }
            set
            {
                this.OnSTATUSChanging(value);
                this._STATUS = value;
                this.OnSTATUSChanged();
                this.OnPropertyChanged("STATUS");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _STATUS;
        partial void OnSTATUSChanging(string value);
        partial void OnSTATUSChanged();
        /// <summary>
        /// There are no comments for Property DELETED in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DELETED
        {
            get
            {
                return this._DELETED;
            }
            set
            {
                this.OnDELETEDChanging(value);
                this._DELETED = value;
                this.OnDELETEDChanged();
                this.OnPropertyChanged("DELETED");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DELETED;
        partial void OnDELETEDChanging(string value);
        partial void OnDELETEDChanged();
        /// <summary>
        /// There are no comments for Property QTY_DELIVERED in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> QTY_DELIVERED
        {
            get
            {
                return this._QTY_DELIVERED;
            }
            set
            {
                this.OnQTY_DELIVEREDChanging(value);
                this._QTY_DELIVERED = value;
                this.OnQTY_DELIVEREDChanged();
                this.OnPropertyChanged("QTY_DELIVERED");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _QTY_DELIVERED;
        partial void OnQTY_DELIVEREDChanging(global::System.Nullable<decimal> value);
        partial void OnQTY_DELIVEREDChanged();
        /// <summary>
        /// There are no comments for Property LAST_MODIFIED_DATE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LAST_MODIFIED_DATE
        {
            get
            {
                return this._LAST_MODIFIED_DATE;
            }
            set
            {
                this.OnLAST_MODIFIED_DATEChanging(value);
                this._LAST_MODIFIED_DATE = value;
                this.OnLAST_MODIFIED_DATEChanged();
                this.OnPropertyChanged("LAST_MODIFIED_DATE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LAST_MODIFIED_DATE;
        partial void OnLAST_MODIFIED_DATEChanging(string value);
        partial void OnLAST_MODIFIED_DATEChanged();
        /// <summary>
        /// There are no comments for Property DELIVERY_COMPLETE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DELIVERY_COMPLETE
        {
            get
            {
                return this._DELIVERY_COMPLETE;
            }
            set
            {
                this.OnDELIVERY_COMPLETEChanging(value);
                this._DELIVERY_COMPLETE = value;
                this.OnDELIVERY_COMPLETEChanged();
                this.OnPropertyChanged("DELIVERY_COMPLETE");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DELIVERY_COMPLETE;
        partial void OnDELIVERY_COMPLETEChanging(string value);
        partial void OnDELIVERY_COMPLETEChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
