//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/16/2021 6:40:27 PM
namespace production.pu.XS_PU_COMMODITY_CLASSIFICATION
{
    
    /// <summary>
    /// There are no comments for XS_PU_COMMODITY_CLASSIFICATION in the schema.
    /// </summary>
    public partial class XS_PU_COMMODITY_CLASSIFICATION : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new XS_PU_COMMODITY_CLASSIFICATION object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public XS_PU_COMMODITY_CLASSIFICATION(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for COMMODITY_CLASS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<COMMODITY_CLASSType> COMMODITY_CLASS
        {
            get
            {
                if ((this._COMMODITY_CLASS == null))
                {
                    this._COMMODITY_CLASS = base.CreateQuery<COMMODITY_CLASSType>("COMMODITY_CLASS");
                }
                return this._COMMODITY_CLASS;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<COMMODITY_CLASSType> _COMMODITY_CLASS;
        /// <summary>
        /// There are no comments for COMMODITY_CLASS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCOMMODITY_CLASS(COMMODITY_CLASSType cOMMODITY_CLASSType)
        {
            base.AddObject("COMMODITY_CLASS", cOMMODITY_CLASSType);
        }
    }
    /// <summary>
    /// There are no comments for production.pu.XS_PU_COMMODITY_CLASSIFICATION.COMMODITY_CLASSType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class COMMODITY_CLASSType
    {
        /// <summary>
        /// Create a new COMMODITY_CLASSType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static COMMODITY_CLASSType CreateCOMMODITY_CLASSType(string ID)
        {
            COMMODITY_CLASSType cOMMODITY_CLASSType = new COMMODITY_CLASSType();
            cOMMODITY_CLASSType.ID = ID;
            return cOMMODITY_CLASSType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PART_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PART_NO
        {
            get
            {
                return this._PART_NO;
            }
            set
            {
                this.OnPART_NOChanging(value);
                this._PART_NO = value;
                this.OnPART_NOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PART_NO;
        partial void OnPART_NOChanging(string value);
        partial void OnPART_NOChanged();
        /// <summary>
        /// There are no comments for Property SITE_NO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SITE_NO
        {
            get
            {
                return this._SITE_NO;
            }
            set
            {
                this.OnSITE_NOChanging(value);
                this._SITE_NO = value;
                this.OnSITE_NOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SITE_NO;
        partial void OnSITE_NOChanging(string value);
        partial void OnSITE_NOChanged();
        /// <summary>
        /// There are no comments for Property COMMODITY_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMODITY_ID
        {
            get
            {
                return this._COMMODITY_ID;
            }
            set
            {
                this.OnCOMMODITY_IDChanging(value);
                this._COMMODITY_ID = value;
                this.OnCOMMODITY_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMODITY_ID;
        partial void OnCOMMODITY_IDChanging(string value);
        partial void OnCOMMODITY_IDChanged();
        /// <summary>
        /// There are no comments for Property COMMODITY_NAME in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMODITY_NAME
        {
            get
            {
                return this._COMMODITY_NAME;
            }
            set
            {
                this.OnCOMMODITY_NAMEChanging(value);
                this._COMMODITY_NAME = value;
                this.OnCOMMODITY_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMODITY_NAME;
        partial void OnCOMMODITY_NAMEChanging(string value);
        partial void OnCOMMODITY_NAMEChanged();
        /// <summary>
        /// There are no comments for Property COMMODITY_DESC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string COMMODITY_DESC
        {
            get
            {
                return this._COMMODITY_DESC;
            }
            set
            {
                this.OnCOMMODITY_DESCChanging(value);
                this._COMMODITY_DESC = value;
                this.OnCOMMODITY_DESCChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _COMMODITY_DESC;
        partial void OnCOMMODITY_DESCChanging(string value);
        partial void OnCOMMODITY_DESCChanged();
        /// <summary>
        /// There are no comments for Property VALID_FROM in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VALID_FROM
        {
            get
            {
                return this._VALID_FROM;
            }
            set
            {
                this.OnVALID_FROMChanging(value);
                this._VALID_FROM = value;
                this.OnVALID_FROMChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VALID_FROM;
        partial void OnVALID_FROMChanging(string value);
        partial void OnVALID_FROMChanged();
        /// <summary>
        /// There are no comments for Property VALID_TO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VALID_TO
        {
            get
            {
                return this._VALID_TO;
            }
            set
            {
                this.OnVALID_TOChanging(value);
                this._VALID_TO = value;
                this.OnVALID_TOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VALID_TO;
        partial void OnVALID_TOChanging(string value);
        partial void OnVALID_TOChanged();
        /// <summary>
        /// There are no comments for Property CREATED_BY in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CREATED_BY
        {
            get
            {
                return this._CREATED_BY;
            }
            set
            {
                this.OnCREATED_BYChanging(value);
                this._CREATED_BY = value;
                this.OnCREATED_BYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CREATED_BY;
        partial void OnCREATED_BYChanging(string value);
        partial void OnCREATED_BYChanged();
        /// <summary>
        /// There are no comments for Property CREATED_ON in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CREATED_ON
        {
            get
            {
                return this._CREATED_ON;
            }
            set
            {
                this.OnCREATED_ONChanging(value);
                this._CREATED_ON = value;
                this.OnCREATED_ONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CREATED_ON;
        partial void OnCREATED_ONChanging(string value);
        partial void OnCREATED_ONChanged();
        /// <summary>
        /// There are no comments for Property CHANGED_ON in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CHANGED_ON
        {
            get
            {
                return this._CHANGED_ON;
            }
            set
            {
                this.OnCHANGED_ONChanging(value);
                this._CHANGED_ON = value;
                this.OnCHANGED_ONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CHANGED_ON;
        partial void OnCHANGED_ONChanging(string value);
        partial void OnCHANGED_ONChanged();
        /// <summary>
        /// There are no comments for Property STATUS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string STATUS
        {
            get
            {
                return this._STATUS;
            }
            set
            {
                this.OnSTATUSChanging(value);
                this._STATUS = value;
                this.OnSTATUSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _STATUS;
        partial void OnSTATUSChanging(string value);
        partial void OnSTATUSChanged();
    }
}
