/* Auto Generated Code By AutoCodeGen Jabil © 2019 */


using QSS.eIQC.Domain.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace QSS.eIQC.IntegrationTests.Core.MoqData
{
    public static class SAPPartInspectionPlanMoq
    {
        public static SAPPartInspectionPlan[] SAPPartInspectionPlans = new[] {
            new SAPPartInspectionPlan { Id = 1,
                         PartNo= "PartNo 1",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 1",
                         GenWI= "GenWI 1",
                         IP= "IP 1",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 1",
                         Manufacturer= "Manufacturer 1",
                         PartDescription= "PartDescription 1",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 1",                     
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 1",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 2,
                         PartNo= "PartNo 2",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 2",
                         GenWI= "GenWI 2",
                         IP= "IP 2",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 2",
                         Manufacturer= "Manufacturer 2",
                         PartDescription= "PartDescription 2",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 2",
                       
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 2",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 3,
                         PartNo= "PartNo 3",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 3",
                         GenWI= "GenWI 3",
                         IP= "IP 3",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 3",
                         Manufacturer= "Manufacturer 3",
                         PartDescription= "PartDescription 3",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 3",
                        
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 3",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 4,
                         PartNo= "PartNo 4",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 4",
                         GenWI= "GenWI 4",
                         IP= "IP 4",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 4",
                         Manufacturer= "Manufacturer 4",
                         PartDescription= "PartDescription 4",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 4",
                       
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 4",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 5,
                         PartNo= "PartNo 5",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 5",
                         GenWI= "GenWI 5",
                         IP= "IP 5",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 5",
                         Manufacturer= "Manufacturer 5",
                         PartDescription= "PartDescription 5",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 5",
                        
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 5",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 6,
                         PartNo= "PartNo 6",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 6",
                         GenWI= "GenWI 6",
                         IP= "IP 6",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 6",
                         Manufacturer= "Manufacturer 6",
                         PartDescription= "PartDescription 6",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 6",
                      
                        SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 6",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
       },
            new SAPPartInspectionPlan { Id = 7,
                         PartNo= "PartNo 7",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 7",
                         GenWI= "GenWI 7",
                         IP= "IP 7",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 7",
                         Manufacturer= "Manufacturer 7",
                         PartDescription= "PartDescription 7",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 7",
                         
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 7",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 8,
                         PartNo= "PartNo 8",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 8",
                         GenWI= "GenWI 8",
                         IP= "IP 8",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 8",
                         Manufacturer= "Manufacturer 8",
                         PartDescription= "PartDescription 8",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 8",
                       
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 8",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 9,
                         PartNo= "PartNo 9",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 9",
                         GenWI= "GenWI 9",
                         IP= "IP 9",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 9",
                         Manufacturer= "Manufacturer 9",
                         PartDescription= "PartDescription 9",
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 9",
                         
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 9",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
            new SAPPartInspectionPlan { Id = 10,
                         PartNo= "PartNo 10",
                         CommodityId= 0,
                         DivisionModelNumber= "DivisionModelNumber 10",
                         GenWI= "GenWI 10",
                         IP= "IP 10",
                         IsSafePart= false,
                         JabilOwnerContact= "JabilOwnerContact 10",
                         Manufacturer= "Manufacturer 10",
                         PartDescription= "PartDescription 10",                         
                         ProductLifeCycleStageId= 0,
                         RefDoc= "RefDoc 10",
                        
                         SupplierId= 0,
                         SupplierContactId= 0,
                         WorkCellId= 0,
                         ApproveRejectedDate= DateTimeOffset.Now,
                         ApproveRejectedId= 0,
                         AssignToUserId= 0,
                         Comment= "Comment 10",
                         StateTypeId= 0,
                         SubmittedByUserId= 0,
                         SubmittedDate= DateTimeOffset.Now,
        },
        };
    }
}
